services:
  - type: web
    name: phoenix-md
    repo: https://github.com/AbhishekSuresh2/Phoenix-Bot.git
    branch: main
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: RENDER_APP_NAME
        sync: false
        required: true
      - key: RENDER_API
        sync: false
        required: true
      - key: SESSION_ID
        sync: false
        required: true
      - key: PREFIX
        value: .
        required: false
      - key: MODE
        value: public
        required: false
      - key: START_MSG
        value: true
        required: false
     - key: ERROR_MSG
        value: true
        required: false   
     - key: AUTO_STATUS_VIEW
        value: false
        required: false
     - key: AUTO_REACT
        value: false
        required: false    
      - key: SUDO
        value: 919074692450, 918157993101
        required: false
      - key: AUDIO_DATA
        value: Phoenix-MD;Abhishek Suresh;https://i.ibb.co/tHWJrz3/IMG-20231128-WA0005.jpg
        required: false
      - key: STICKER_DATA
        value: ğŸ¯á´˜Êœá´á´‡É´Éªx-á´á´…;á´€Ê™ÊœÉªêœ±Êœá´‡á´‹ êœ±á´œÊ€á´‡êœ±ÊœğŸ€
        required: false  
      - key: BOT_INFO
        value: á´˜Êœá´á´‡É´Éªx-á´á´…;á´€Ê™ÊœÉªêœ±Êœá´‡á´‹ êœ±á´œÊ€á´‡êœ±Êœ;919074692450;https://i.ibb.co/tHWJrz3/IMG-20231128-WA0005.jpg
        required: false
      - key: ALIVE_DATA
        value: ğŸ‘‹ Êœá´‡Ê &sender, Éª á´ *á´˜Êœá´á´‡É´Éªx-á´á´… á´¡Êœá´€á´›êœ±á´€á´˜á´˜ Ê™á´á´›* á´€ÊŸÉªá´ á´‡ É´á´á´¡!\n\nğŸ“Œ á´›Êá´˜á´‡ *menu* á´›á´ É¢á´‡á´› á´Ê á´„á´á´á´á´€É´á´… ÊŸÉªêœ±á´›.\n\n*á´˜ÊŸá´€á´›êœ°á´Ê€á´:* &platform\n*Ê€á´œÉ´á´›Éªá´á´‡:* &runtime;https://i.ibb.co/tHWJrz3/IMG-20231128-WA0005.jpg
        required: false
       
        
